In [1]:
import numpy as np
mylist = [1,2,3,4]
type(np.array(mylist))
arr = np.array(mylist)
arr

array([1, 2, 3, 4])

In [3]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])